/// <summary>
/// This class was procedurally generated by the Weaver Shader Linker (http://u3d.as/rt5).
/// </summary>
public static class SimpleSunShader
{
    /// <summary>Shader Name (for use with <see cref="UnityEngine.Shader.Find(string)"/>)</summary>
    public const string Name = "Unlit/Simple Sun";

    /// <summary>Mode [Float]</summary>
    public static readonly int _Mode = UnityEngine.Shader.PropertyToID("_Mode");

    /// <summary>Primary Color [Color]</summary>
    public static readonly int _Color = UnityEngine.Shader.PropertyToID("_Color");

    /// <summary>Secondary Color [Color]</summary>
    public static readonly int _SecondaryColor = UnityEngine.Shader.PropertyToID("_SecondaryColor");

    /// <summary>Ball Radius [Range(Default=0.45, Min=0, Max=0.5)]</summary>
    public static readonly int _BallRadius = UnityEngine.Shader.PropertyToID("_BallRadius");

    /// <summary>Ball Sharpness [Float]</summary>
    public static readonly int _BallSharpness = UnityEngine.Shader.PropertyToID("_BallSharpness");

    /// <summary>Ray Frequency [Float]</summary>
    public static readonly int _RayFrequency = UnityEngine.Shader.PropertyToID("_RayFrequency");

    /// <summary>Ray Intensity [Float]</summary>
    public static readonly int _RayIntensity = UnityEngine.Shader.PropertyToID("_RayIntensity");

    /// <summary>Ray Roughness [Range(Default=1, Min=0, Max=1.5)]</summary>
    public static readonly int _RayRoughness = UnityEngine.Shader.PropertyToID("_RayRoughness");

    /// <summary>Speed [Float]</summary>
    public static readonly int _Speed = UnityEngine.Shader.PropertyToID("_Speed");

    /// <summary>Noise [2D Texture]</summary>
    public static readonly int _Noise = UnityEngine.Shader.PropertyToID("_Noise");

    /// <summary>Texture Scale [Float]</summary>
    public static readonly int _TextureScale = UnityEngine.Shader.PropertyToID("_TextureScale");

    /// <summary>Keyword: _MODE_BASIC</summary>
    public const string _MODE_BASIC = "_MODE_BASIC";

    /// <summary>Keyword: _MODE_DUAL_COLOR</summary>
    public const string _MODE_DUAL_COLOR = "_MODE_DUAL_COLOR";

    /// <summary>Keyword: _MODE_TEXTURED</summary>
    public const string _MODE_TEXTURED = "_MODE_TEXTURED";
}